### ISSUE TITLE
tcp_test.go: Flakey tests

### ISSUE THREAD

**Issue by TheTincho** [prometheus/blackbox_exporter#285]
Hey, it's me again :-)

The blackbox_exporter is failing tests in Debian, and these seem to be related to CPU contention. 

I had already disabled `TestTCPConnectionWithTLS` as it produced deadlocks; somehow the goroutine blocks in the Accept call, while the main routine is waiting at the synchronization channel read. I pressume the Accept is not called early enough: https://buildd.debian.org/status/fetch.php?pkg=prometheus-blackbox-exporter&arch=armhf&ver=0.11.0%2Bds-2&stamp=1513326591&raw=0

Now I am getting `use of closed network connection` panics in `TestTCPConnectionQueryResponseIRC`, which I don't understand at all.

**Comment by brian-brazil** [comment]
Is this still an issue? Looking at the current builds the failures are for more obscure architectures, and don't appear related to the blackbox exporter itself.

**Comment by NightTsarina** [comment]
I will have to check. After opening this report, I disabled all the reports in tcp_test.go, so I don't know if they are still failing, and they were not failing always anyway

**Comment by NightTsarina** [comment]
I have disabled my patch locally, and they don't seem to fail. In the next package upload I will leave them enabled and see if it fails in some architecture

**Comment by NightTsarina** [comment]
Nevermind, I have just tested in armhf, and that error is still present. But this is not a flaky test, it fails consistently:
```
=== RUN   TestTCPConnectionQueryResponseStartTLS
    TestTCPConnectionQueryResponseStartTLS: tcp_test.go:294: TCP module failed, expected success.
--- FAIL: TestTCPConnectionQueryResponseStartTLS (24.92s)
panic: Error accepting on socket: accept tcp 127.0.0.1:44977: use of closed network connection

goroutine 1435 [running]:
github.com/prometheus/blackbox_exporter/prober.TestTCPConnectionQueryResponseStartTLS.func1(0x636d60, 0x13259a0, 0x1402000, 0x47b, 0x7c0, 0x1348000, 0x68b, 0x7c0, 0x141a1c0)
	/home/tina/prometheus-blackbox-exporter/obj-arm-linux-gnueabihf/src/github.com/prometheus/blackbox_exporter/prober/tcp_test.go:250 +0x6f4
created by github.com/prometheus/blackbox_exporter/prober.TestTCPConnectionQueryResponseStartTLS
	/home/tina/prometheus-blackbox-exporter/obj-arm-linux-gnueabihf/src/github.com/prometheus/blackbox_exporter/prober/tcp_test.go:247 +0x540
FAIL	github.com/prometheus/blackbox_exporter/prober	47.391s
FAIL
```

**Comment by brian-brazil** [comment]
> TCP module failed, expected success.

That's the failure, the probe is failing before it even gets to do any probing I'd expect. Most likely something with the network setup on that machine. Does a strace show what's happening?
