### ISSUE TITLE
run time error on make

### ISSUE THREAD

**Issue by skangayam** [prometheus/blackbox_exporter#42]
I am using go1.6.2 and centos6.8 
This is the error being reflected on screen when i run make.

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x93d400, 0xc8200100a0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.vendoredImportPath(0xc8201dc800, 0xc820250331, 0x20, 0x0, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:466 +0x713
main.loadImport(0xc820250331, 0x20, 0xc820053f20, 0x58, 0xc8201dc800, 0xc82049b788, 0xc820250630, 0x1, 0x1, 0x1, ...)
    /usr/local/go/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc8201dc800, 0xc82049b788, 0xc8202dc000, 0x0, 0x0, 0x4)
    /usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc820176121, 0x2e, 0xc820144690, 0x22, 0xc820027800, 0xc82049b788, 0xc820176330, 0x1, 0x1, 0x1, ...)
    /usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc820027800, 0xc82049b788, 0xc820420e00, 0x0, 0x0, 0xc)
    /usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc82013a3a3, 0x3, 0xc82000a034, 0x22, 0x0, 0xc82049b788, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0xc82013a3a3, 0x3, 0xc82049b788, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:1639 +0x13d8
main.packagesAndErrors(0xc82008c000, 0x14, 0x14, 0x0, 0x0, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:1684 +0x531
main.packages(0xc82000a260, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:1652 +0x86
main.runList(0xc8a6a0, 0xc82000a260, 0x1, 0x1)
    /usr/local/go/src/cmd/go/list.go:186 +0x1f6
main.main()
    /usr/local/go/src/cmd/go/main.go:181 +0x783
>> formatting code
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x93d400, 0xc82000e0d0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.vendoredImportPath(0xc820199000, 0xc8201ef4a1, 0x20, 0x0, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:466 +0x713
main.loadImport(0xc8201ef4a1, 0x20, 0xc8203a99e0, 0x58, 0xc820199000, 0xc820179838, 0xc8201ef5f0, 0x1, 0x1, 0x1, ...)
    /usr/local/go/src/cmd/go/pkg.go:336 +0xe52
main.(*Package).load(0xc820199000, 0xc820179838, 0xc82016e380, 0x0, 0x0, 0x4)
    /usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0xc82014b651, 0x2e, 0xc82010bbf0, 0x22, 0xc820135000, 0xc820179838, 0xc82014b860, 0x1, 0x1, 0x1, ...)
    /usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.(*Package).load(0xc820135000, 0xc820179838, 0xc82012b500, 0x0, 0x0, 0xc)
    /usr/local/go/src/cmd/go/pkg.go:953 +0x4397
main.loadImport(0x9e0b58, 0x1, 0xc820014004, 0x22, 0x0, 0xc820179838, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/cmd/go/pkg.go:377 +0x84e
main.loadPackage(0x9e0b58, 0x1, 0xc820179838, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:1639 +0x13d8
main.packagesAndErrors(0xc82013a1f0, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:1684 +0x531
main.packages(0xc82000a270, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/cmd/go/pkg.go:1652 +0x86
main.runFmt(0xc8a060, 0xc82000a270, 0x0, 0x0)
    /usr/local/go/src/cmd/go/fmt.go:38 +0x8d
main.main()
    /usr/local/go/src/cmd/go/main.go:181 +0x783
make: *** [format] Error 2
```

**Comment by brian-brazil** [comment]
This sounds like an issue with your version of go. Try upgrading.
