### ISSUE TITLE
Error while building blackbox_exporter in Docker builder image

### ISSUE THREAD

**Issue by devops-42** [prometheus/blackbox_exporter#713]
### Host operating system: output of `uname -a`
Builder image for go (Docker): golang:1.15.5-buster

### blackbox_exporter version: output of `blackbox_exporter -version`

No success, `make` failed with error

### What is the blackbox.yml module config.
Not relevant

### What is the prometheus.yml scrape config.
Not relevant

### What logging output did you get from adding `&debug=true` to the probe URL?
Not relevant

### What did you do that produced an error?
I tried to build blackbox_exporter with Docker using a builder image. My Dockerfile looks like:

```
FROM golang:1.15.5-buster

ARG ARCH="amd64"
ARG OS="linux"

USER root

RUN apt-get update && apt-get upgrade && \
      git \
      gcc \
      curl

RUN git clone https://github.com/prometheus/blackbox_exporter.git /go/src/github.com/prometheus/blackbox_exporter

ENV GOPATH=/go

WORKDIR /go/src/github.com/prometheus/blackbox_exporter

RUN make
[...]
```

When starting the Docker build the last step aborts with a failure (most likely in testing DNS). 

### What did you expect to see?
Issuing the `make` command finished successfully. Below an example of a successful build on a VM:

```
[...]
>> running check for unused/missing packages in go.mod
GO111MODULE=on go mod tidy
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
>> building binaries
GO111MODULE=on /root/go/bin/promu build --prefix /root/blackbox_exporter 
 >   blackbox_exporter
>> running all tests
GO111MODULE=on go test -race  -mod=vendor ./...
ok  	github.com/prometheus/blackbox_exporter	(cached)
ok  	github.com/prometheus/blackbox_exporter/config	(cached)
ok  	github.com/prometheus/blackbox_exporter/prober	(cached)
```

### What did you see instead?
```
[...]
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
curl -s -L https://github.com/prometheus/promu/releases/download/v0.5.0/promu-0.5.0.linux-amd64.tar.gz | tar -xvzf - -C /tmp/tmp.rwLEuU3EZH
promu-0.5.0.linux-amd64/
promu-0.5.0.linux-amd64/promu
promu-0.5.0.linux-amd64/NOTICE
promu-0.5.0.linux-amd64/LICENSE
mkdir -p /go/bin
cp /tmp/tmp.rwLEuU3EZH/promu-0.5.0.linux-amd64/promu /go/bin/promu
rm -r /tmp/tmp.rwLEuU3EZH
>> building binaries
GO111MODULE=on /go/bin/promu build --prefix /go/src/github.com/prometheus/blackbox_exporter 
 >   blackbox_exporter
>> running all tests
GO111MODULE=on go test -race  -mod=vendor ./...
ok  	github.com/prometheus/blackbox_exporter	0.054s
ok  	github.com/prometheus/blackbox_exporter/config	0.051s
--- FAIL: TestRecursiveDNSResponse (0.00s)
    dns_test.go:158: Test 0 had unexpected result: false
--- FAIL: TestAuthoritativeDNSResponse (0.00s)
    dns_test.go:358: Test 0 had unexpected result: false
--- FAIL: TestServfailDNSResponse (0.00s)
    dns_test.go:432: Test 1 had unexpected result: false
--- FAIL: TestDNSProtocol (0.00s)
    dns_test.go:480: DNS protocol: "udp", preferred "ip6" connection test failed, expected success.
2020/11/26 16:22:10 http: TLS handshake error from 127.0.0.1:36980: remote error: tls: bad certificate
panic: test timed out after 10m0s

goroutine 1233 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:1509 +0x11c
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:168 +0x52

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0001906c0, 0xf14861, 0x18, 0xf3cba0, 0x1)
	/usr/lib/golang/src/testing/testing.go:1091 +0x739
testing.runTests.func1(0xc0001906c0)
	/usr/lib/golang/src/testing/testing.go:1334 +0xa7
testing.tRunner(0xc0001906c0, 0xc0000e3d38)
	/usr/lib/golang/src/testing/testing.go:1039 +0x1ec
testing.runTests(0xc00000f380, 0x15cb3e0, 0x24, 0x24, 0x0)
	/usr/lib/golang/src/testing/testing.go:1332 +0x528
testing.(*M).Run(0xc000074200, 0x0)
	/usr/lib/golang/src/testing/testing.go:1249 +0x440
main.main()
	_testmain.go:114 +0x224

goroutine 1289 [chan receive, 9 minutes]:
github.com/prometheus/blackbox_exporter/prober.TestTCPConnectionWithTLS(0xc000229200)
	/go/src/github.com/prometheus/blackbox_exporter/prober/tcp_test.go:162 +0xa92
testing.tRunner(0xc000229200, 0xf3cba0)
	/usr/lib/golang/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1090 +0x701

goroutine 1290 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f05e30e1f18, 0x72, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00025f018, 0x72, 0x0, 0x0, 0xf085ae)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00025f000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:384 +0x2c9
net.(*netFD).accept(0xc00025f000, 0xc000341c20, 0xc000341c1c, 0x11d1d00)
	/usr/lib/golang/src/net/fd_unix.go:238 +0x56
net.(*TCPListener).accept(0xc0003c2340, 0x0, 0x1561f99, 0x1561f99)
	/usr/lib/golang/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc0003c2340, 0x1561f99, 0x1561f99, 0x26, 0xc000341de8)
	/usr/lib/golang/src/net/tcpsock.go:261 +0x50
github.com/prometheus/blackbox_exporter/prober.TestTCPConnectionWithTLS.func1()
	/go/src/github.com/prometheus/blackbox_exporter/prober/tcp_test.go:113 +0x95
created by github.com/prometheus/blackbox_exporter/prober.TestTCPConnectionWithTLS
	/go/src/github.com/prometheus/blackbox_exporter/prober/tcp_test.go:157 +0x9ac
FAIL	github.com/prometheus/blackbox_exporter/prober	600.020s
FAIL
make: *** [Makefile.common:172: common-test] Error 1
```

What I'm doing wrong?

Thanks for your help!

**Comment by brian-brazil** [comment]
That DNS test fails sometimes (nothing to do with Docker), I've yet to fully determine why. Any insights there would be appreciated.

**Comment by mem** [comment]
@devops-42 where you able to fix this issue?

I was just trying to reproduce with the provided Dockerfile, but that fails. After fixing it, it fails in a different way (one of the tests is trying to resolve ipv6.google.com and it fails not sure why).

**Comment by devops-42** [comment]
Hi @mem,

to be honest I haven't tried again since the build update #722 But within the next days I'll give it a try again and will inform you about the success :)

**Comment by electron0zero** [comment]
I tried it with latest golang image, and it worked. closing the issue.

here is my Dockerfile:
```Dockerfile
FROM golang:1.23.4-bookworm

ARG ARCH="amd64"
ARG OS="linux"

USER root

RUN apt-get update -y && apt-get upgrade -y && apt-get install git gcc curl -y

RUN git clone https://github.com/prometheus/blackbox_exporter.git /tmp/blackbox_exporter

WORKDIR /tmp/blackbox_exporter

RUN make build
```

build logs:
```bash
➜ docker build .
[+] Building 55.7s (9/9) FINISHED                                                                                                     docker:colima
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 366B                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/golang:1.23.4-bookworm                                                                      2.3s
 => [internal] load .dockerignore                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                0.0s
 => [1/5] FROM docker.io/library/golang:1.23.4-bookworm@sha256:2e838582004fab0931693a3a84743ceccfbfeeafa8187e87291a1afea457ff7a               28.4s
 => => resolve docker.io/library/golang:1.23.4-bookworm@sha256:2e838582004fab0931693a3a84743ceccfbfeeafa8187e87291a1afea457ff7a                0.0s
 => => sha256:2e838582004fab0931693a3a84743ceccfbfeeafa8187e87291a1afea457ff7a 9.10kB / 9.10kB                                                 0.0s
 => => sha256:ba1dd0e85e0bf7e5cb632a24bbc3ec0060700bc5be9273b05d7e059950225037 48.33MB / 48.33MB                                               6.0s
 => => sha256:fd63102cac360c09802a29bab13f15de711e8bd1a730d419c66110513700983c 64.35MB / 64.35MB                                              20.2s
 => => sha256:98f66c0f9a34f98f31ceec0be5cdc77dd77eb7a050280b079462a0cfdc22b9a9 2.32kB / 2.32kB                                                 0.0s
 => => sha256:e3b811b0aa52884991c6d5944ea68fa43e84ab3083751b07f04a10bb19bf6514 2.82kB / 2.82kB                                                 0.0s
 => => sha256:92b12b0dccf212c795e61e16dcc85f0caa01c231281e3287400bd334ffedb5ff 23.41MB / 23.41MB                                               9.8s
 => => sha256:47f0760d52ed73adddb3508ddcb5b6593cb64ca56a1ff03102d680fcf2358d2d 86.34MB / 86.34MB                                              23.9s
 => => extracting sha256:ba1dd0e85e0bf7e5cb632a24bbc3ec0060700bc5be9273b05d7e059950225037                                                      1.1s
 => => extracting sha256:92b12b0dccf212c795e61e16dcc85f0caa01c231281e3287400bd334ffedb5ff                                                      0.3s
 => => sha256:39f8f326b04424eb2027d1f0e3255fe568d71a5567f894a08cd86605ebe51c58 70.67MB / 70.67MB                                              22.7s
 => => extracting sha256:fd63102cac360c09802a29bab13f15de711e8bd1a730d419c66110513700983c                                                      1.3s
 => => sha256:df3aad8f12f66060f1575c7562f8831493595038c34f14527da5ffae2ea0332e 126B / 126B                                                    21.1s
 => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                                                      21.4s
 => => extracting sha256:47f0760d52ed73adddb3508ddcb5b6593cb64ca56a1ff03102d680fcf2358d2d                                                      1.1s
 => => extracting sha256:39f8f326b04424eb2027d1f0e3255fe568d71a5567f894a08cd86605ebe51c58                                                      2.6s
 => => extracting sha256:df3aad8f12f66060f1575c7562f8831493595038c34f14527da5ffae2ea0332e                                                      0.0s
 => => extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1                                                      0.0s
 => [2/5] RUN apt-get update -y && apt-get upgrade -y && apt-get install git gcc curl -y                                                       2.1s
 => [3/5] RUN git clone https://github.com/prometheus/blackbox_exporter.git /tmp/blackbox_exporter                                             1.7s
 => [4/5] WORKDIR /tmp/blackbox_exporter                                                                                                       0.0s
 => [5/5] RUN make build                                                                                                                      20.1s
 => exporting to image                                                                                                                         1.1s
 => => exporting layers                                                                                                                        1.1s
 => => writing image sha256:036d4898bc47feb7127d1256a8056c12e28c2b8a73e7ed16c76e028c788052cb                                                   0.0s
```
